### ISSUE TITLE
Typo in ReadMe

### ISSUE THREAD

**Issue by KlausUnger** [spring-projects-experimental/spring-boot-testjars#37]
I'm wondering if the snippets for maven dependencies in Readme.md are correct. I'm pretty sure that `scope` has to be exchanged with `version`.

```
<dependency>
    <groupId>org.springframework.experimental.boot</groupId>
    <artifactId>spring-boot-testjars</artifactId>
    <scope>0.0.1</scope>
</dependency>
```

It actually appears twice!

I'll open a PR for it

**Comment by rwinch** [comment]
Thanks for reporting the issue. I've closed in favor of gh-38
